name: Test pro_venv.py

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"            

      - name: Run scaffold (creates venv, installs deps, writes files)
        run: |
          python pro_venv.py

      - name: Smoke test (launcher + app)
        run: |
          python main.py --help || true
          python main.py
